# This is a basic workflow to help you get started with Actions

name: Vue to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v3
    - id: Build-Vue
      uses: ricardobiundo/ReactPagesAction@1.0.1
      with:
        username: 'ricardobiundo'
        reponame: 'curriculum'
        cname: 'koffiecode.com'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        useyarn: true
